### ISSUE TITLE
can edit saved text by inserting characters before it

### ISSUE THREAD

**Issue by foggynight** [letterlock/brr-deprecated#1]
When you insert characters before saved text, the inserted characters become "locked" and push out the saved characters, which become "unlocked".

**Comment by letterlock** [comment]
thanks for reporting this!  
i'm unable to confirm the inserted text becoming "locked", but once you enter text, regardless of where you enter it, that amount of text becomes editable, which is not intended.  
would you be able to confirm for me whether or not the text you've inserted becomes "locked" as you say?  
either way, i plan to address this by forcing the cursor to always be at the end of the file when inserting or deleting text.

**Comment by foggynight** [comment]
Ah it wasn't behaving quite like I thought it was. Once you insert text before committed text it starts to behave strangely, you can delete the same number of committed characters as what you inserted etc.

I think forcing the cursor to be at the end of the file is a good solution.

**Comment by letterlock** [comment]
this should be solved with the newest commit.  

i'll close this issue as any problems that look like this one would now most likely be an entirely new bug.
